### ISSUE TITLE
Questions about reproduction

### ISSUE THREAD

**Issue by jacklin64** [TIGER-AI-Lab/UniIR#15]
Hi, first of all, thanks for the great resource. I'm now trying to reproduce the results of UNIIR CLIP score fusion in Table11. I have two questions regarding to the results.

1. An obvious difference between my reproduction and paper results on MSCOCO task1 and Visual News task4. Is there any possible issue here? 
2. I observe slight variations in my reproduction and paper results on the other tasks. Does the variation come from randomly sampled instructions and is this an acceptable variations?

![Screenshot 2024-06-25 at 1 55 57 PM](https://github.com/TIGER-AI-Lab/UniIR/assets/18071510/0c18cc3d-9baf-4988-ab92-afbea051bd6c)

**Comment by lim142857** [comment]
Hi,

Thank you for reaching out and for your interest in reproducing our results. I appreciate your efforts and am happy to clarify the discrepancies you've encountered.

Regarding the differences observed in MSCOCO task 1 and Visual News task 4, it's important to note that the released checkpoint was retrained and is not the same one used to produce the initial results published on Arxiv. Unfortunately, the original checkpoint was lost during a server system cleanup.

From our subsequent experiments with the new checkpoint, we've noticed variations across different tasks—some show improved performance, while others do not perform as well. We believe these discrepancies are likely due to the random sampling of instructions during training. To provide a benchmark, the average R@1, R@5, and R@10 across M-BEIR for CLIP_SF reported in Table 11 on Arxiv were 30.5, 50.3, and 59.8, respectively. The results from the new checkpoint are 28.9, 48.7, and 58.0(From my experiments). Given that this represents a degradation of less than 2%, we consider these variations to be within an acceptable range.

We have updated the results table in the version of the paper currently under review, and we plan to update the Arxiv version once the review process is complete.
